# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    php_errors:
        log: true

    serializer:
        enable_annotations: true
        name_converter: serializer.name_converter.camel_case_to_snake_case

when@test:
    framework:
        test: true
