parameters:
    app.content_fetcher.cache_response: '%env(bool:APP_CONTENT_FETCHER_CACHE_RESPONSE)%'
    app.content_fetcher.cache_path: '%kernel.cache_dir%/corona'
    app.corona_data_path: '%kernel.project_dir%/data/corona'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $cacheDir: '%kernel.cache_dir%'
            $projectDir: '%kernel.project_dir%'
    _instanceof:
        App\Scraper\Scraper:
            tags: ['app.scraper']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Dto/'
            - '../src/Kernel.php'

    App\Command\AppFetchCoronaCasesCommand:
        arguments:
            $scraper: !tagged_iterator 'app.scraper'
            $dataPath: '%app.corona_data_path%'

    App\HttpClient\CacheClient:
        arguments:
            $cacheResponse: '%app.content_fetcher.cache_response%'
            $cachePath: '%app.content_fetcher.cache_path%'

    App\Serializer\DecoratingObjectNormalizer:
        decorates: 'serializer.normalizer.object'
        arguments:
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'
