name: Tests

env:
    php_version: '8.1'

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   uses: actions/checkout@v3

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer packages
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install php dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Install php ci dependencies
                run: composer install --working-dir=dev-ops/ci --prefer-dist --no-progress

            -   name: Install phpunit
                run: php bin/phpunit install --configuration dev-ops/ci/config/phpunit.xml.dist

            -   name: Clear cache
                run: php bin/console cache:clear

            -   name: Archive application
                working-directory: ../
                run: |
                    tar -czf application.tar.gz --exclude=".git" --exclude="node_modules" -C ${{ github.workspace }} .
                    mv application.tar.gz ${{ github.workspace }}/

            -   name: Upload prepared application
                uses: actions/upload-artifact@v2
                with:
                    name: applicationArchive
                    path: application.tar.gz
                    if-no-files-found: error
                    retention-days: 1

    lint:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Download prepared application
                uses: actions/download-artifact@v2
                with:
                    name: applicationArchive

            -   name: Unpack application
                run: tar -xzf application.tar.gz --strip=1

            -   name: Validate container
                run: php bin/console lint:container

            -   name: Validate yaml files
                run: php bin/console lint:yaml config --parse-tags

    php-cs-fixer:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Download prepared application
                uses: actions/download-artifact@v2
                with:
                    name: applicationArchive

            -   name: Unpack application
                run: tar -xzf application.tar.gz --strip=1

            -   name: Run php-cs-fixer
                run: php dev-ops/ci/vendor/bin/php-cs-fixer fix --config=dev-ops/ci/config/.php-cs-fixer.dist.php --dry-run

    phpstan:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Download prepared application
                uses: actions/download-artifact@v2
                with:
                    name: applicationArchive

            -   name: Unpack application
                run: tar -xzf application.tar.gz --strip=1

            -   name: Run phpstan
                run: php -d memory_limit=-1 dev-ops/ci/vendor/bin/phpstan analyze --configuration=dev-ops/ci/config/phpstan.neon.dist

    phpunit:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Download prepared application
                uses: actions/download-artifact@v2
                with:
                    name: applicationArchive

            -   name: Unpack application
                run: tar -xzf application.tar.gz --strip=1

            -   name: Run test suite
                run: php bin/phpunit --configuration dev-ops/ci/config/phpunit.xml.dist

    cleanup:
        runs-on: ubuntu-latest
        needs:
            - build
            - lint
            - php-cs-fixer
            - phpstan
            - phpunit
        if: ${{ always() }}
        steps:
            -   name: Delete unecessary artifacts
                uses: geekyeggo/delete-artifact@v1
                with:
                    name: applicationArchive
                    failOnError: false
