name: Tests

env:
    php_version: '8.1'

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   uses: actions/checkout@v3

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer packages
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install php dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Install php ci dependencies
                run: composer install --working-dir=dev-ops/ci --prefer-dist --no-progress

            -   name: Install phpunit
                run: php bin/phpunit install --configuration dev-ops/ci/config/phpunit.xml.dist

            -   name: Clear cache
                run: php bin/console cache:clear

            -   name: Store build
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

    lint:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Restore build
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

            -   name: Validate container
                run: php bin/console lint:container

            -   name: Validate yaml files
                run: php bin/console lint:yaml config --parse-tags

    php-cs-fixer:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Restore build
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

            -   name: Run php-cs-fixer
                run: php dev-ops/ci/vendor/bin/php-cs-fixer fix --config=dev-ops/ci/config/.php-cs-fixer.dist.php --dry-run

    phpstan:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Restore build
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

            -   name: Run phpstan
                run: php -d memory_limit=-1 dev-ops/ci/vendor/bin/phpstan analyze --configuration=dev-ops/ci/config/phpstan.neon.dist

    phpunit:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php_version }}

            -   name: Restore build
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

            -   name: Run test suite
                run: php bin/phpunit --configuration dev-ops/ci/config/phpunit.xml.dist
